### ISSUE TITLE
Game Crash Randomly

### ISSUE THREAD

**Issue by JoyousCreeper1059** [meza/SoundsBeGone#10]
I've gotten this crash several times, and it's always the same error mentioning soundsbegone, not sure if this mod causes it, but it's the only thing I can think of, it usually happens when I land on a block, right when the sound happens it freezes, then crashes shortly after

I have uploaded the crash report: https://mclo.gs/9djykYo

**Comment by meza** [comment]
Thanks, I'll look into it!

**Comment by meza** [comment]
@JoyousCreeper1059 it _should_ be fixed in the latest versions! https://modrinth.com/mod/soundsbegone/versions

**Comment by JoyousCreeper1059** [comment]
yay!!!
TYSM!!!!!!

**Comment by meza** [comment]
I _hope_ it works. It's difficult to reproduce but I have a pretty good idea of what the issue was. There is a slight chance I haven't actually fixed it so please keep an eye on it and let me know :)
