### ISSUE TITLE
Server crash on disconnect

### ISSUE THREAD

**Issue by yuma-dev** [meza/SoundsBeGone#14]
Im hosting the server by just starting over lan and if one user disconnects, it crashes my game
crashlog: https://mclo.gs/YE6Ef7S

**Comment by meza** [comment]
Thanks for this! I know exactly what this is, I'll get it fixed some time this week!

**Comment by meza** [comment]
:tada: This issue has been resolved for **Minecraft: 1.20.1** in version 1.2.5 :tada:\n\nThe release is available on [GitHub release](<github_release_url>)

**Comment by meza** [comment]
Try this, I think it should work: https://modrinth.com/mod/soundsbegone/version/T0ISkF2V

**Comment by meza** [comment]
:tada: This issue has been resolved for **Minecraft: 1.20.2** in version 1.2.5 :tada:\n\nThe release is available on [GitHub release](<github_release_url>)

**Comment by meza** [comment]
:tada: This issue has been resolved for **Minecraft: 1.20.4** in version 1.3.4 :tada:\n\nThe release is available on [GitHub release](<github_release_url>)

**Comment by meza** [comment]
:tada: This issue has been resolved for **Minecraft: 1.21** in version 1.3.4 :tada:\n\nThe release is available on [GitHub release](<github_release_url>)
